pipeline {
    agent any
    
    stages{
        stage("Git Clone"){
            steps{
                echo "Cloning Code"
                git url: "https://github.com/shreyasd-git/Jenkins.git", branch: "J_notes-app"
            }
        }
        
        stage("Build"){
            steps{
                echo "Building Docker IMG"
                //sh "docker build -f /var/lib/jenkins/workspace/DjangoNotesapp/project1/django-notes-app-main/Dockerfile -t my-notes-app1 ."
                sh "docker build -f ${env.workspace}/project1/django-notes-app-main/Dockerfile -t my-notes-app1 ."
            }
        }
        
        stage("Pushing to DockerHub"){
            steps{
                echo "Pushig img to Docker Hub"
                withCredentials([usernamePassword(credentialsId: 'DockerHub', passwordVariable: 'DockerHubPass', usernameVariable: 'DockerHubUser')])
                {
                    sh "docker tag my-notes-app1 ${env.DockerHubUser}/my-notes-app1:latest"
                    sh "docker login -u ${env.DockerHubUser} -p ${env.DockerHubPass}"
                    sh "docker push ${env.DockerHubUser}/my-notes-app1:latest"
                }
            }
        }
        
        stage("Deploy"){
            steps{
                echo "Deploying Container"
                // sh "docker run -d -p 8000:8000 sdevarkar/my-notes-app1:latest"
                sh "docker-compose -f ${env.workspace}/project1/django-notes-app-main/docker-compose.yml down && docker-compose -f ${env.workspace}/project1/django-notes-app-main/docker-compose.yml up -d"
            }
        }
    }
}
